#!/bin/csh
set c=1
set s=1

rm job_* 
rm launchJob
touch launchJob

while ( $c <= 100 )
#echo "qsub -P P_t2k -l s_vmem=1G,ct=04:10:00,s_fsize=1G,sps=1 job_$c.sh" >> launchJob
#echo "qsub -P P_t2k -o /sps/t2k/sbologne/fitter/ccqe_rep/ccqeana/trunk/bin/output_$c.txt -e /sps/t2k/sbologne/fitter/ccqe_rep/ccqeana/trunk/bin/outerr_$c.txt -l ct=48:00:00,s_fsize=4G,sps=1 job_$c.sh" >> launchJob
echo "qsub -P P_t2k -o /sps/t2k/sbologne/fitter/ccqe_rep/ccqeana/trunk/bin/output_$c.txt -e /sps/t2k/sbologne/fitter/ccqe_rep/ccqeana/trunk/bin/outerr_$c.txt -l ct=24:00:00,s_fsize=4G,sps=1 job_$c.sh" >> launchJob

echo "job  number " $c
cp templateJob job_$c.sh

@ s *= 87 
echo "with seed " $s

sed -i 's/'"-s 12345"'/'"-s $s"'/g' job_$c.sh
sed -i 's/'"prova.root"'/'"ccqe_results_$c.root"'/g' job_$c.sh
chmod +x job_$c.sh

@ c = $c + 1
@ s = $c

chmod +x launchJob

end
